server.port=8007
spring.application.name=tournament-registration

# CORS
spring.web.cors.allowed-origins=http://localhost:3007
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
